name: deploy to the cloud

on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: deploy

env:
  RUST_BACKTRACE: 1

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - run: teraform plan
